module.exports = {
	words: [
		"COVID",
		"COVID-19",
		"coronavirus",
		"face masks",
		"facial covering",
		"masks",
		"vaccine",
		"quarantine",
		"sickness",
		"pandemic",
		"social distancing",
		"flatten the curve",
		"flattening the curve",
		"antibodies",
		"community spread",
		"containment",
		"fatality rate",
		"ventilators",
		"BiPap machine",
		"testing",
		"wash hands",
		"washing hands",
		"asymptomatic",
		"CDC",
		"Centers for Disease Control and Prevention",
		"contact tracing",
		"6 feet",
		"immunity",
		"herd immunity",
		"incubation period",
		"immunocompromised",
		"isolation",
		"mitigation",
		"patient zero",
		"self-quarantine",
		"respirator",
		"screening",
		"stay at home order",
		"shelter in place",
		"symptoms",
		"symptom",
		"respiratory disease",
		"virus",
		"WHO",
		"World Health Organization",
		"zoonotic",
		"virtual meetings",
		"zoom bombing",
		"coronavirus testing",
		"droplet transmission",
		"drive through testing",
		"personal protective equipment",
		"physical distancing",
		"super spreader",
		"telemedicine",
		"underlying medical conditions",
		"clean",
		"cough",
		"fever",
		"mask",
		"spread",
		"wash",
		"self isolating",
		"crisis",
		"the rona",
		"covidiot",
		"work from home",
		"working from home",
		"patient",
		"patients",
		"quaranteam",
		"case fatality rate",
		"close contact",
		"toilet paper",
		"hand sanitizer",
		"response",
		"cordon sanitaire",
		"elective surgeries",
		"essential activities",
		"symptomatic",
		"viral",
		"outbreak",
		"disease",
		"emerging disease",
		"transmission",
		"person to person contact",
		"rate of infection",
		"health care workers",
		"lockdown",
		"restrictions",
		"vaccine research",
		"mandatory masks",
		"test positive",
		"test negative",
		"number of cases",
		"public health",
		"exponential",
		"morgues filled",
		"surge",
		"virtual classes",
		"reopening",
		"permanent closure",
		"effective response",
		"confirmed cases",
		"travel ban",
		"2 week quarantine",
		"2 weeks",
		"misinformation",
		"shut down",
		"test results",
		"recession",
		"vulnerable population",
		"stimulus payments",
		"travel advisories",
		"disinfect",
		"higher risk",
		"exposure",
		"limit exposure",
		"antibody testing",
		"viral test",
		"nose swab",
		"shortness of breath",
		"fatigue",
		"muscle aches",
		"body aches",
		"headache",
		"loss of sense of smell",
		"loss of taste",
		"sore throat",
		"congestion",
		"runny nose",
		"nausea",
		"vomiting",
		"diarrhea",
		"difficulty breathing",
		"prevention",
	],
};
